---
repos:
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.6.5
    hooks:
      - id: conventional-commits

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # misc
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # yaml
      - id: check-yaml

  - repo: "local"
    hooks:
      - id: "mix-format"
        name: "Format Elixir files"
        description: "Formats Elixir files with 'mix format'"
        language: "system"
        entry: "mix format"
        files: "\\.(?:exs|ex|heex)$"
        require_serial: true
      - id: "mix-test"
        name: "Test Elixir files"
        description: "Runs Elixir tests with 'mix test'"
        language: "system"
        entry: "./support/scripts/test-elixir"
        files: "\\.(?:exs|ex|heex)$"
        require_serial: true
