---
services:
  phoenix:
    environment:
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
    networks:
      - "traefik-global-proxy"
      - "phoenix-quiz-game"
    ports:
      - "${PORT:?}"

networks:
  traefik-global-proxy:
    external: true
  phoenix-quiz-game:
