---
services:
  phoenix:
    environment:
      DATABASE_URL: "${DATABASE_URL:?}"
    networks:
      - "traefik-global-proxy"
      - "postgres"
      - "phoenix-quiz-game"
    ports:
      - "${PORT:?}"
    labels:
      # enable gzip compression
      - "traefik.http.middlewares.phoenix-quiz-game--compress.compress=true"
      - "traefik.http.routers.phoenix-quiz-game.middlewares=phoenix-quiz-game--compress"

networks:
  traefik-global-proxy:
    external: true
  postgres:
    external: true
  # the 'phoenix-quiz-game' network is only used when running phoenix and
  # postgres as part of the same container orchestration service
  phoenix-quiz-game:
