---
services:
  postgres:
    hostname: "postgres"
    networks:
      - "phoenix-quiz-game"
    ports:
      - "${POSTGRES_PORT:-5432}"

networks:
  traefik-global-proxy:
    external: true
  phoenix-quiz-game:
