---
services:
  phoenix:
    environment:
      DATABASE_URL: "${DATABASE_URL:?}"
    networks:
      - "traefik-global-proxy"
      - "postgres" # use this if you are running a postgres container outside of this project's compose service
    ports:
      - "${PORT:?}"
    labels:
      # enable gzip compression
      - "traefik.http.middlewares.phoenix-quiz-game--compress.compress=true"
      - "traefik.http.routers.phoenix-quiz-game.middlewares=phoenix-quiz-game--compress"

networks:
  traefik-global-proxy:
    external: true
  postgres: # use this if you are running a postgres container outside of this project's compose service
    external: true
