---
services:
  phoenix:
    environment:
      DATABASE_URL: "${DATABASE_URL:?}"
    networks:
      - "traefik-global-proxy"
      - "phoenix-quiz-game"
    ports:
      - "${PORT:?}"

networks:
  traefik-global-proxy:
    external: true
  phoenix-quiz-game:
