---
services:
  phoenix:
    depends_on:
      - "postgres"
    networks:
      - "phoenix-quiz-game"
  postgres:
    networks:
      - "phoenix-quiz-game"
    ports:
      - "5432"

networks:
  phoenix-quiz-game:
