---
services:
  phoenix:
    image: "docker.io/arcanemachine/phoenix-quiz-game:${IMAGE_TAG:-latest}"
    restart: "always"
    environment:
      # phoenix
      PHX_HOST: "${PHX_HOST:?}"
      PORT: "${PORT:?}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:?}"

      # captcha
      HCAPTCHA_PRIVATE_KEY: "${HCAPTCHA_PRIVATE_KEY:?}"
      HCAPTCHA_PUBLIC_KEY: "${HCAPTCHA_PUBLIC_KEY:?}"

      # database
      DATABASE_URL: "${DATABASE_URL:?}"

      # email
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET: "${AWS_SECRET}"
      EMAIL_RECIPIENT_CONTACT_FORM: "${EMAIL_RECIPIENT_CONTACT_FORM:?}"
