---
services:
  phoenix:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phoenix-quiz-game.rule=Host(`${PHX_HOST:?}`)"
      - "traefik.http.routers.phoenix-quiz-game.entrypoints=web"

      # enable gzip compression
      - "traefik.http.middlewares.phoenix-quiz-game--compress.compress=true"
      - "traefik.http.routers.phoenix-quiz-game.middlewares=phoenix-quiz-game--compress"
